name: Salisbury Student Housing
favicon: null
layout_spectrum: 0.4112395439296961
typography_spectrum: 0.5245539739262313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7747195181436837
  lightness: 0.3321708112489432
  saturation: 0.21261684992350638
  rhythmicContrast: 0.5572772531304508
purpose: []
